#开发环境配置文件

# 服务配置
server:
  servlet:
    context-path: /ky
  port: 8081

# 业务配置
bus:
  api:
    baseUrl: http://172.66.66.201:1021
  file:
    baseDir: D:/ky/file
    max-size: 50 * 1024 * 1024

# 日志配置
logging:
  file:
    path: D:/ky/log/