#开发环境配置文件

# 服务配置
server:
  port: 8081
  servlet:
    context-path: /ky

# spring配置
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

# 业务配置
bus:
  api:
    baseUrl: http://172.66.66.201:1021
  file:
    baseDir: D:/ky/file
    max-size: 10485760

# 日志配置
logging:
  file:
    path: D:/ky/log/